language: node_js
node_js:
  - "0.10"
install:
  - gem install sass 
  - gem install compass
  - npm install -g grunt-cli
  - npm install
  - grunt
  - node_modules/json-server/bin/index.js --watch assets/data/response.json
